services:
  - type: web
    name: receitasbackend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://sistema-receitas-frontend.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Origin, X-Requested-With, Content-Type, Accept, Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
